--- 
sa_active_merchant_password: !str 
  str: 
  "@_rails_html_safe": false
sa_active_merchant_login: !str 
  str: 
  "@_rails_html_safe": false
sa_active_merchant_gateway: !str 
  str: 
  "@_rails_html_safe": false
