--- 
sa_mailing_port: !str
  str: "993"
  "@_rails_html_safe": false
sa_mailing_user_name: !str
  str: 
  "@_rails_html_safe": false
sa_mailer_host: !str
  str: 
  "@_rails_html_safe": false
sa_mailer_enable_ssl: !str
  str: "0"
  "@_rails_html_safe": false
sa_mailer_password: !str 
  str: 
  "@_rails_html_safe": false
